### ISSUE TITLE
Subshell environment

### ISSUE THREAD

**Issue by chemoish** [RickWong/wait-run#2]
So I am continually exploring the SSR/CSS stuff we spoke about before and it finally has lead me to this…

`wait-run --pattern "build/index.js" "(cd build && node index)"`

This doesn't work with wait-run, but do you know if its possible to execute subshells within your setup?

---

Additional information:

The location you execute `node` determines your static paths, relatively. This ends up effecting webpack's `publicPath` configuration.

However, if you run `concurrently --kill-others "npm run watch-server" "npm run watch-client"`—manually wait—then run the command above, it works.

**Comment by RickWong** [comment]
You should try just-wait. It's more flexible.

**Comment by chemoish** [comment]
Works thanks!

``` json
"scripts": {
  "start": "node ./node_modules/concurrently/src/main --kill-others \"npm run watch-server\" \"npm run watch-client\" \"npm run start-server\"",
  "build-client": "node ./node_modules/webpack/bin/webpack --config webpack/webpack.config.client-build",
  "build-server": "node ./node_modules/webpack/bin/webpack --config webpack/webpack.config.server-build",
  "start-server": "node ./node_modules/just-wait/bin/just-wait --pattern \"build/index.js\" && (cd build && node ./index)",
  "watch-client": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack/webpack.config.client-start",
  "watch-server": "rm -rf build && node ./node_modules/webpack/bin/webpack --colors --config webpack/webpack.config.server-start",
  "test": "karma start --single-run"
}
```
1. server runs on localhost:8080 output to build folder
2. client runs on localhost:8081 output to build/static
3. server css is delivered from build/index.css
4. server fonts is delivered from build/*.ttf
5. prod follows same structure as development
